/*
 * hw.h
 *
 *  Created on: 12 aug 2019
 *      Author: Alex
 */

#ifndef HW_H_
#define HW_H_

/*
 * This is a fusion file to join c++ project and main.c file generated by CubeMX
 */
#include "stat.h"
#include "iron.h"
#include "encoder.h"
#include "display.h"
#include "config.h"

extern I2C_HandleTypeDef 	hi2c1;

class HW {
	public:
		HW(void) : cfg(&hi2c1),
			encoder(ENCODER_R_GPIO_Port, ENCODER_R_Pin, ENCODER_L_GPIO_Port, ENCODER_L_Pin)		{ }
		CFG_STATUS	init(void);
		CFG			cfg;
		DSPL		dspl;
		IRON		iron;
		RENC		encoder;
};

#endif
